version: "3.9"

services:
  retroconvert:
    build: .
    container_name: retroconvert
    restart: unless-stopped
    ports:
      - "5004:5000"
    volumes:
      - /mnt/Storage/MassStorage/RetroConvertTest/Roms:/roms
      - retroconvert_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  retroconvert_data:
